// 블로그 포스트 데이터
const blogPosts = [
  {
    id: 19,
    title: '재무설계사 AFPK 자격증 안내: 시험과목·취득 절차·CFP와의 차이',
    category: '자격증',
    tags: ['AFPK', '재무설계사', 'CFP', '자격시험', '금융자격증'],
    date: '2026-09-21',
    thumbnail: '../assets/icons/afpk-financial-planning.svg',
    excerpt: 'AFPK의 교육·시험·인증 절차와 모듈별 과목·합격기준을 살펴보고, CFP와의 응시요건·실무경험·시험 방식 차이를 비교합니다.',
    file: 'afpk-financial-planner-guide.md',
    readTime: '5분',
  },
  {
    id: 18,
    title: '해방 이후 대한민국 현대사: 사건으로 읽는 1945~2025년',
    category: '역사',
    tags: ['대한민국 현대사', '광복', '민주화', '경제사', '주요 사건'],
    date: '2026-09-20',
    thumbnail: '../assets/icons/korea-modern-history-timeline.svg',
    excerpt: '광복과 정부 수립, 전쟁, 산업화와 민주화, 외환위기부터 최근 헌정 사건까지 주요 사건을 시간순으로 정리합니다.',
    file: 'korea-modern-history-by-events.md',
    readTime: '9분',
  },
  {
    id: 17,
    title: '운전면허 학과시험 안내: 응시자격·합격기준·준비물·문제은행',
    category: '생활정보',
    tags: ['운전면허', '학과시험', '1종 보통', '2종 보통', '문제은행'],
    date: '2026-09-20',
    thumbnail: '../assets/icons/driver-license-written-test.svg',
    excerpt: '1·2종 보통 운전면허 학과시험의 합격기준과 준비물, 교육·신체검사 순서, 공식 문제은행 이용 방법을 정리합니다.',
    file: 'driver-license-written-test-guide.md',
    readTime: '5분',
  },
  {
    id: 16,
    title: '정보시스템감리사 자격증 안내: 응시자격·필기시험·면접·교육',
    category: '자격증',
    tags: ['정보시스템감리사', '국가공인 민간자격', '응시자격', '필기시험'],
    date: '2026-09-19',
    thumbnail: '../assets/icons/information-systems-auditor.svg',
    excerpt: 'NIA 공식 안내를 기준으로 정보시스템감리사 응시자격, 필기 5과목, 면접과 교육 절차, 비용과 공고 확인 방법을 정리합니다.',
    file: 'information-systems-auditor.md',
    readTime: '5분',
  },
  {
    id: 15,
    title: '정보보안기사 자격증 안내: 시험과목·응시자격·2026년 시험일정',
    category: '자격증',
    tags: ['정보보안기사', '국가기술자격', '시험일정', '정보보안'],
    date: '2026-09-18',
    thumbnail: '../assets/icons/information-security-engineer.svg',
    excerpt: '정보보안기사의 필기·실기 시험과목, 응시자격, 2026년 제1·2·4회 접수·시험·합격 발표 일정을 KCA 공식 안내를 기준으로 정리합니다.',
    file: 'information-security-engineer-2026.md',
    readTime: '4분',
  },
  {
    id: 14,
    title: '역대 정부의 부동산 대책: 공급·규제·세금·대출·임대차 정책',
    category: '부동산',
    tags: ['부동산', '주택 정책', '역대 정부', '공급', '규제'],
    date: '2026-09-18',
    thumbnail: 'images/korea-housing-policy-by-government/housing-policy.webp',
    excerpt: '박정희 정부부터 이재명 정부까지 주택 공급, 거래 규제, 세금·대출, 임차인 보호 정책의 흐름을 비교합니다. 2026년 9월 기준.',
    file: 'korea-housing-policy-by-government.md',
    readTime: '9분',
  },
  {
    id: 13,
    title: 'Android ADB 명령어 모음: 연결부터 로그·화면 캡처까지',
    category: 'Android',
    tags: ['Android', 'ADB', 'Debugging', 'CLI'],
    date: '2026-09-17',
    thumbnail: '../assets/icons/android-adb.svg',
    excerpt: 'ADB 설치와 기기 연결부터 앱 설치·실행, Logcat, 화면 캡처와 녹화, 파일 전송, 무선 디버깅까지 자주 쓰는 명령어를 정리합니다.',
    file: 'android-adb-commands.md',
    readTime: '7분',
  },
  {
    id: 12,
    title: 'Docker 입문: 이미지 빌드부터 컨테이너 정리까지',
    category: 'DevOps',
    tags: ['Docker', 'Container', 'Image', 'CLI'],
    date: '2026-09-16',
    thumbnail: 'images/docker-getting-started/docker_rect.png',
    excerpt: 'Docker의 이미지와 컨테이너 개념을 이해하고, 빌드·실행·상태 확인·로그 조회·리소스 정리에 필요한 기본 명령어를 알아봅니다.',
    file: 'docker-getting-started.md',
    readTime: '6분',
  },
  {
    id: 11,
    title: 'yt-dlp를 이용한 유튜브 영상 다운로드 방법',
    category: 'DevOps',
    tags: ['yt-dlp', 'YouTube', 'FFmpeg', 'CLI'],
    date: '2026-09-09',
    thumbnail: 'images/yt-dlp-youtube-download/yt-dlp.png',
    excerpt: 'yt-dlp 설치부터 영상 화질 선택, MP3 변환, 자막과 재생목록 다운로드까지 자주 사용하는 명령어를 알아봅니다.',
    file: 'yt-dlp-youtube-download.md',
    readTime: '7분',
  },
  {
    id: 10,
    title: 'Ubuntu 입문: 기본 명령어와 패키지 관리',
    category: 'Ubuntu',
    tags: ['Ubuntu', 'Linux', 'Terminal', 'APT'],
    date: '2026-08-21',
    thumbnail: '../assets/icons/ubuntu.svg',
    excerpt: 'Ubuntu를 처음 사용하는 사람을 위해 시스템 업데이트, 기본 터미널 명령어, 패키지 관리 방법을 간단히 정리합니다.',
    file: 'ubuntu-getting-started.md',
    readTime: '4분',
  },
  {
    id: 9,
    title: 'vscode 프로젝트 설정가이드',
    category: 'VS Code',
    tags: ['VS Code', 'Theme', 'Settings'],
    date: '2026-08-09',
    thumbnail: 'images/vscode-project-settings/vscode-logo.webp',
    excerpt: 'VS Code의 색 테마를 빠르게 변경하고 확장 테마를 설치하거나 settings.json에서 일부 색상을 직접 설정하는 방법을 알아봅니다.',
    file: 'vscode-project-settings.md',
    readTime: '2분',
  },
  {
    id: 8,
    title: "Let's Encrypt로 Cloudflare DNS 환경에서 와일드카드 인증서 발급하기",
    category: 'DevOps',
    tags: ["Let's Encrypt", 'Cloudflare', 'Nginx', 'SSL', 'Wildcard'],
    date: '2026-07-20',
    thumbnail: 'images/letsencrypt-cloudflare-wildcard/lets-encrypt.png',
    excerpt: 'Cloudflare DNS-01 Challenge와 Certbot을 이용해 mypage.com 와일드카드 인증서를 발급하고 자동 갱신하는 방법을 알아봅니다.',
    file: 'letsencrypt-cloudflare-wildcard.md',
    readTime: '5분',
  },
  {
    id: 1,
    title: 'Ultra VNC를 이용한 원격제어 시스템 구축',
    category: 'DevOps',
    tags: ['VNC', 'Remote', 'Docker', 'noVNC'],
    date: '2024-11-25',
    thumbnail: 'images/vnc/UltraVNC.webp',
    excerpt: '오픈소스 원격 데스크톱 솔루션 Ultra VNC의 설치부터 Repeater, noVNC를 활용한 웹 기반 원격제어까지 완벽 가이드.',
    file: 'vnc-remote-control.md',
    readTime: '12분',
  },
  {
    id: 2,
    title: 'Google Fit API 완벽 가이드',
    category: 'Android',
    tags: ['Google Fit', 'Android', 'API', 'OAuth'],
    date: '2024-11-25',
    thumbnail: 'images/google-fit/logo.jpg',
    excerpt: 'Google Fit API의 구조와 활용법을 알아봅니다. Recording, Sensors, History API를 이용한 피트니스 데이터 수집 방법을 상세히 설명합니다.',
    file: 'google-fit.md',
    readTime: '8분',
  },
  {
    id: 3,
    title: '클린 아키텍처 검토 - Android 리팩토링',
    category: 'Android',
    tags: ['Clean Architecture', 'Refactoring', 'Kotlin', 'Compose'],
    date: '2024-11-25',
    thumbnail: 'images/clean-architecture/logo.jpeg',
    excerpt: '증가하는 사용자 요구사항에 유연하게 대처하기 위한 Legacy 소스의 Clean Architecture 기반 리팩토링 작업을 검토합니다.',
    file: 'clean-architecture.md',
    readTime: '10분',
  },
  {
    id: 4,
    title: 'WPF Application Data 파일',
    category: 'Windows',
    tags: ['WPF', 'C#', '.NET', 'XAML'],
    date: '2023-09-19',
    thumbnail: 'https://miro.medium.com/v2/resize:fit:1272/1*JoXc43sxqIa4oYIfwbFX7w.png',
    excerpt: 'WPF 애플리케이션에서 사용하는 Resource Files, Content Files, Site of Origin Files의 차이점과 활용 방법을 알아봅니다.',
    file: 'wpf-application-data-files.md',
    readTime: '5분',
  },
  {
    id: 5,
    title: '.NET 기반 WPF앱에서 Winform 사용하기',
    category: 'Windows',
    tags: ['WPF', 'WinForms', 'C#', '.NET'],
    date: '2023-10-26',
    thumbnail: 'https://miro.medium.com/v2/resize:fit:1400/1*08xD4YeCXecnwUf-aq8HIA.png',
    excerpt: 'WPF 프로젝트에서 Windows Forms를 함께 사용하는 방법을 알아봅니다. UseWindowsForms 설정만 추가하면 간단하게 해결됩니다.',
    file: 'wpf-winform-integration.md',
    readTime: '3분',
  },
  {
    id: 6,
    title: 'WPF 하이브리드앱 만들기',
    category: 'Windows',
    tags: ['WPF', 'CefSharp', 'Hybrid', '.NET'],
    date: '2023-10-11',
    thumbnail: 'https://miro.medium.com/v2/resize:fit:1272/1*712Z8jstt_PJW90M7_151w.png',
    excerpt: 'WPF 애플리케이션에 CefSharp을 활용하여 웹 브라우징 기능을 추가하는 방법을 알아봅니다. Nuget을 통한 설치부터 구현까지 상세히 설명합니다.',
    file: 'wpf-hybrid-app.md',
    readTime: '4분',
  },
  {
    id: 7,
    title: '갤럭시워치3 (Tizen) CLI 사용법',
    category: 'Tizen',
    tags: ['Tizen', 'Galaxy Watch', 'CLI', 'Samsung'],
    date: '2022-04-24',
    thumbnail: 'https://miro.medium.com/v2/resize:fit:1400/1*SoubQ3pQdm4jTIq8N0-eGg.png',
    excerpt: 'Tizen Studio CLI를 활용하여 갤럭시워치3 앱을 빌드, 패키징, 설치하는 전체 과정을 명령어 기반으로 상세히 설명합니다.',
    file: 'galaxy-watch-tizen-cli.md',
    readTime: '3분',
  },
];

// 카테고리 목록 추출
const categories = ['전체', ...new Set(blogPosts.map((post) => post.category))];

// 카테고리별 포스트 수 계산
function getCategoryCount(category) {
  if (category === '전체') return blogPosts.length;
  return blogPosts.filter((post) => post.category === category).length;
}
